/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    boolean empezo = false;
    ArbolB ab = new ArbolB();
    Nodo aux = null;
    
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEmpezar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pregunta = new javax.swing.JTextArea();
        preguntaLabel = new javax.swing.JLabel();
        respuestaLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnInstrucciones = new javax.swing.JButton();
        controlesLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSi = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnNo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnVerArbol = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnBorrarArbol = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        cargarTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Adivinador");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        btnSalir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnEmpezar.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpezar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEmpezar.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpezar.setText("Empezar");
        btnEmpezar.setBorderPainted(false);
        btnEmpezar.setContentAreaFilled(false);
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        pregunta.setEditable(false);
        pregunta.setBackground(new java.awt.Color(255, 255, 255));
        pregunta.setColumns(20);
        pregunta.setRows(5);
        jScrollPane1.setViewportView(pregunta);

        preguntaLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        preguntaLabel.setForeground(new java.awt.Color(0, 0, 0));
        preguntaLabel.setText("Pregunta");

        respuestaLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        respuestaLabel.setForeground(new java.awt.Color(0, 0, 0));
        respuestaLabel.setText("Respuesta");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        btnInstrucciones.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(0, 0, 0));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        controlesLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        controlesLabel.setForeground(new java.awt.Color(0, 0, 0));
        controlesLabel.setText("Controles");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        btnSi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSi.setForeground(new java.awt.Color(0, 0, 0));
        btnSi.setText("Si");
        btnSi.setBorderPainted(false);
        btnSi.setContentAreaFilled(false);
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSi, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSi, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        btnNo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnNo.setForeground(new java.awt.Color(0, 0, 0));
        btnNo.setText("No");
        btnNo.setBorderPainted(false);
        btnNo.setContentAreaFilled(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        btnVerArbol.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnVerArbol.setForeground(new java.awt.Color(0, 0, 0));
        btnVerArbol.setText("Ver Preguntas");
        btnVerArbol.setBorderPainted(false);
        btnVerArbol.setContentAreaFilled(false);
        btnVerArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVerArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVerArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        btnBorrarArbol.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBorrarArbol.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrarArbol.setText("Borrar Preguntas");
        btnBorrarArbol.setBorderPainted(false);
        btnBorrarArbol.setContentAreaFilled(false);
        btnBorrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBorrarArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBorrarArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        cargarTxt.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cargarTxt.setForeground(new java.awt.Color(0, 0, 0));
        cargarTxt.setText("Cargar Preguntas");
        cargarTxt.setBorderPainted(false);
        cargarTxt.setContentAreaFilled(false);
        cargarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlesLabel)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respuestaLabel)
                    .addComponent(preguntaLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlesLabel)
                    .addComponent(preguntaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(respuestaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        empezo = true;
        if(ab.isEmpty()) { //Si el arbol esta vacío se comienza con esta pregunta
            pregunta.setText("Buscas un animal?");
        } else { //Si no esta vacio se comienza con la pregunta del primer nodo
            aux = ab.getRoot(); //Se define aux como la raiz del arbol
            pregunta.setText(ab.getRoot().getInfo());
        }
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
        if(empezo) { //Si se presiono empezar entra en el codigo para moverse por las preguntas
            if(!ab.isEmpty()) { //Si el arbol esta vacío pondra las pregunas por defecto
                if(!ab.isLeaf(aux) && aux.getLeft() != null){ //Si el nodo tiene hijos 
                    aux = aux.getLeft(); //El nodo auxiliar se rueda a la izquirda (Rama "si")
                    String siguiente = aux.getInfo(); //Se toma la información de la pregunta que contiene el nodo
                    pregunta.setText(siguiente + "?"); //Se inserta en el text field con un signo de interrogación
                } else { //Si es un nodo final, se confirma como respuesta correcta y animal adivinado
                    JOptionPane.showMessageDialog(null, "Ganaste"); 
                    pregunta.setText(" "); //Reinicia el text field
                }
            } else {
                pregunta.setText("Es un pájaro?"); //Pregunta por defecto
                //revisar
                ab.addRoot("Es un pájaro?");
                aux = ab.getRoot();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha presionado el boton de empezar");
        }
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        if(empezo) {
            if(!ab.isEmpty()) { 
                if(!ab.isLeaf(aux) && aux.getRight() != null){
                    aux = aux.getRight();
                    String siguiente = aux.getInfo();
                    pregunta.setText(siguiente + "?");
                } else { //Si la respuesta es no y el nodo es una hoja, se pregunta la respuesta correcta y se actualiza el arbol
                    String respuesta = JOptionPane.showInputDialog(null, "Cual era la respuesta?"); //Respuesta nueva
                    String diferencia = JOptionPane.showInputDialog(null, "Cual es la diferencia?"); //Diferencia entre los animales
                     //Confirmación para ver donde se pone el nuevo nodo (derecha o izquierda)
                    int confirmar = JOptionPane.showConfirmDialog(null, "Para la pregunta " + diferencia + " cual seria la respuesta de " + respuesta);
                    ab.actualizar(respuesta, diferencia, aux, confirmar); //Se llama a la funcion actualizar para agregar los nuevos nodos
                    pregunta.setText(" "); //Se borra el text field
                }
            } else {
                JOptionPane.showMessageDialog(null,"Se busca solo un animal"); //Solo se buscan animales
                pregunta.setText(" ");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha presionado el boton de empezar");
        }
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnVerArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerArbolActionPerformed
        // TODO add your handling code here:
        // muestra grafo
    }//GEN-LAST:event_btnVerArbolActionPerformed

    private void btnBorrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarArbolActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "¿Seguro qué desea borrar la base de datos? Esta acción no se puede revertir.");
        if(confirm == 0){
            ab.vaciarArbol();
            JOptionPane.showMessageDialog(null, "Base de preguntas eliminada.");
        }
    }//GEN-LAST:event_btnBorrarArbolActionPerformed

    private void cargarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarTxtActionPerformed
        // TODO add your handling code here:
        //cargar txt
    }//GEN-LAST:event_cargarTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarArbol;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSi;
    private javax.swing.JButton btnVerArbol;
    private javax.swing.JButton cargarTxt;
    private javax.swing.JLabel controlesLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pregunta;
    private javax.swing.JLabel preguntaLabel;
    private javax.swing.JLabel respuestaLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
      
    String texto = "";

    /**
     *Se recorre el arbol en preorden y se guarda los datos de cada nodo y su padre en un 
     * texto.
     * @param n
     * Nodo a recorrer.
     */
    public void preordenTxt(Nodo n){
        if(n!=null){
            texto+=n.info+","+n.padre.info+"\n";
            preordenTxt(n.left);
            preordenTxt(n.right);
        }
    }
    
    /**
     *Se crea un archivo txt guardando la linea de texto luego de recorrer el árbol.
     * @throws IOException
     * Por si se genera un error.
     */
    public void guardarArbol() throws IOException{
        preordenTxt(ab.getRoot());
//        String nombreTxt = JOptionPane.showInputDialog("Ingrese el nombre del archivo.");//Validar. Todo pegado. Nada que Windows no acepte.
        //Guardar el archivo en la carpeta asignada.
        try {
            File archivo = new File("src\\test\\java\\demo.txt");
            FileWriter fw = new FileWriter(archivo);
                fw.write(texto);
                fw.close();
                JOptionPane.showMessageDialog(null, "Archivo guardado.");
            }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Ocurrio un error.","Error",0);
         } 
    }
    
    /**
     *Lee el archivo de texto y lo separa en de manera que se pueda reconstruir el árbol.
     * @throws IOException
     * Por si se genera un error.
     */
    public void leerArbol ()throws IOException{
        String linea;
        String datos = "";
        String[] listaDatos = null;
        File archivo = new File("src\\test\\java\\demo.txt");
        //Clase para leer los archivos.
        FileReader fr = new FileReader(archivo);
        BufferedReader br = new BufferedReader(fr);
        //Guarda el contenido del archivo en un String datos.
        while((linea = br.readLine()) != null) {
            if (!linea.isEmpty()) {
                datos += linea + "\n";
            }
        }
        //Guarda el contenido del String datos en un Array listaDatos.
        //Cada nueva linea del String datos es un nuevo elemento en el Array.
        if (!"".equals(datos)) {
            listaDatos = datos.split("\n");
        }
        //Recorre el Array para asignarlo a los campos requeridos
        for (int i = 0; i < listaDatos.length; i++) {
            String [] arreglo = listaDatos[i].split(",");
            ab.addHijo(arreglo[0], ab.getRoot());//Crear clase construir arbol
        }
    }
}
